### ISSUE TITLE
Failed to install ModLoader core files error

### ISSUE THREAD

**Issue by T0kyoRa1n** [hylian-modding/ModLoader64#38]
I downloaded and installed modloader 64 making sure I have both VC++ 2017 x86 Runtime Libraries and Node.js x86 Libraries but when I start modloader64-gui.exe I get this error:

Unhandled Error
Error: Cannot find module 'C:/Games/oot-online/ModLoader64/ModLoader/src/version'.
Require stack:
- C:/Games/oot-online/ModLoader64/resources/app/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Timeout.<anonym> (C:/Games/oot-online/ModLoader64/resources/app/index.js:434:21)

What could be happening and what could be the solution?

**Comment by AliceDTRH** [comment]
Use one of these. And apparently most support and stuff is done on their Discord for some reason, I think.

https://modloader64.com/modloader64-gui-stable-appimage.tar.xz

https://cdn.discordapp.com/attachments/562776415595135008/1097677350684074075/Modloader64.7z?ex=668e7bf2&is=668d2a72&hm=157bd2e1bbb07ea566c91a43481b17ee865fe676e64e7b54e725d9d1b3abe39e&
